language: c

env:
  # build and test against the master and devel branches of Nim
  - BRANCH=master
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

matrix:
  allow_failures:
    # ignore failures when building against the devel Nim branch
    - env: BRANCH=devel
  fast_finish: true

install:
  - export CHOOSENIM_CHOOSE_VERSION="#$BRANCH"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y

script:
  - nimble install -y
  - nimble test -y
