name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: restore macOS-latest when choosenim #122 is solved
        # https://github.com/dom96/choosenim/issues/122
        os: [windows-latest, ubuntu-latest]
        nim: [stable, devel]
    name: Nim ${{ matrix.nim }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@master
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-stable
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-stable
      - uses: jiro4989/setup-nim-action@v1.0.1
      - name: Install dependencies
        run: nimble install -y
      - name: Run tests
        run: nimble test
